name: Testing the GitHub Pages publication

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
         
         echo "`git branch`"

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Standard usage
    - uses: actions/jekyll-build-pages@v1.0.7
      with:
        token: ${{ secrets.CODE_MDEV_TOKEN }}

    # Specify the Jekyll source location as a parameter
    - uses: actions/jekyll-build-pages@v1.0.7
      with:
        token: ${{ secrets.CODE_MDEV_TOKEN }}
        source: GITHUB_WORKSPACE

    # Specify the target branch (optional)
    - uses: actions/jekyll-build-pages@v1.0.7
      with:
        token: ${{ secrets.CODE_MDEV_TOKEN }}
        target_branch: 'gh-pages'
